### ISSUE TITLE
discuss what to with sizing

### ISSUE THREAD

**Issue by LokoGod** [LokoGod/ecom-demo#12]
We need to discuss what we are going to need to do about the sizing of the overall components in the pages

**Comment by RavvyS** [comment]
We can measure the components in the pages with google page ruler and for that we can use a site we want to build

<img width="847" alt="Screenshot 2024-06-26 at 14 41 35" src="https://github.com/LokoGod/ecom-demo/assets/156438913/64cbd760-aa77-4ddd-a2ce-f0fcc6629408">
